sudo: required
language: python

services:
- docker

python:
- 3.4

addons:
  postgresql: "9.4"

env:
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="4"

install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm -version
- make -f config/travis .build/dev-requirements.timestamp
- make -f config/travis install

before_script:
- scripts/travis-api-server.sh

script:
- make -f config/travis check

after_failure:
  cat v6_api/nohup.out

after_success:
- make cleanall publish

notifications:
  email: false
